In [5]:
import yfinance as yf
data = yf.Ticker("SPCX")

In [6]:
data.info

{'address1': '1 Rocket Road',
 'city': 'Starbase',
 'state': 'TX',
 'zip': '78521',
 'country': 'United States',
 'phone': '310 363 6000',
 'website': 'https://www.spacex.com',
 'industry': 'Aerospace & Defense',
 'industryKey': 'aerospace-defense',
 'industryDisp': 'Aerospace & Defense',
 'sector': 'Industrials',
 'sectorKey': 'industrials',
 'sectorDisp': 'Industrials',
 'longBusinessSummary': "Space Exploration Technologies Corp. provides satellite-based broadband services in the United States, Ireland, Canada, and internationally. The company's Connectivity segment operates a high-speed, low-latency broadband network powered by various Starlink satellites in low-earth orbit, delivering connectivity to various consumer, enterprise, and government customers through its Starlink offering. Its Space segment designs, manufactures, and launches reusable rockets to provide access to space. It offers launch services for the deployment of payloads to intended orbits for commercial and government customers utilizing Falcon 9 and Falcon Heavy; and launch and development for the development of spacecraft and the provision of launch and mission services for government agency space programs utilizing Falcon 9, Falcon Heavy, Starship, and Dragon. The company's AI segment operates a vertically integrated AI platform spanning a frontier LLM Grok; AI solutions for consumer and enterprise customers; X, a real-time information, entertainment, and free speech platform; and AI computational infrastructure. The company was founded in 2002 and is based in Starbase, Texas.",
 'fullTimeEmployees': 22000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Bret W. Johnsen',
   'age': 56,
   'title': 'CFO & Secretary',
   'yearBorn': 1969,
   'fiscalYear': 2025,
   'totalPay': 825000,
   'exercisedValue': 41906656,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Michael  Sagan',
   'title': 'Senior Director of Legal',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy R. Hughes',
   'title': 'Senior VP of Global Business & Government Affairs',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Richard J. Lee',
   'title': 'Treasurer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'compensationAsOfEpochDate': 1767139200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 157.54,
 'open': 159.725,
 'dayLow': 155.88,
 'dayHigh': 162.16,
 'regularMarketPreviousClose': 157.54,
 'regularMarketOpen': 159.725,
 'regularMarketDayLow': 155.88,
 'regularMarketDayHigh': 162.16,
 'payoutRatio': 0.0,
 'forwardPE': 823.71484,
 'volume': 61257120,
 'regularMarketVolume': 61257120,
 'averageVolume': 169218092,
 'averageVolume10days': 119647080,
 'averageDailyVolume10Day': 119647080,
 'bid': 147.75,
 'ask': 167.0,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 2134218244096,
 'nonDilutedMarketCap': 2134218342276,
 'fiftyTwoWeekLow': 147.11,
 'fiftyTwoWeekHigh': 225.64,
 'allTimeHigh': 225.64,
 'allTimeLow': 147.11,
 'priceToSalesTrailing12Months': 110.57553,
 'fiftyDayAverage': 169.12357,
 'twoHundredDayAverage': 169.12357,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 953212076032,
 'profitMargins': -0.44998002,
 'floatShares': 281190750,
 'sharesOutstanding': 7571396888,
 'sharesShort': 23341117,
 'dateShortInterest': 1781481600,
 'sharesPercentSharesOut': 0.0018000001,
 'heldPercentInsiders': 0.18744,
 'heldPercentInstitutions': 0.00126,
 'shortRatio': 0.06,
 'shortPercentOfFloat': 0.0038,
 'impliedSharesOutstanding': 13174187298,
 'bookValue': 5.956,
 'priceToBook': 27.199463,
 'lastFiscalYearEnd': 1767139200,
 'nextFiscalYearEnd': 1798675200,
 'mostRecentQuarter': 1774915200,
 'netIncomeToCommon': -9356000256,
 'trailingEps': -0.68,
 'forwardEps': 0.19667,
 'enterpriseToRevenue': 49.387,
 'enterpriseToEbitda': 241.32,
 '52WeekChange': 0.0065237284,
 'SandP52WeekChange': 0.20116603,
 'quoteType': 'EQUITY',
 'currentPrice': 162.0,
 'targetHighPrice': 310.0,
 'targetLowPrice': 62.0,
 'targetMeanPrice': 188.57143,
 'targetMedianPrice': 190.0,
 'recommendationMean': 2.0,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 7,
 'totalCash': 23675000832,
 'totalCashPerShare': 4.083,
 'ebitda': 3950000128,
 'totalDebt': 30602999808,
 'quickRatio': 1.088,
 'currentRatio': 1.217,
 'totalRevenue': 19300999168,
 'debtToEquity': 73.597,
 'revenuePerShare': 6.075,
 'grossProfits': 9424000000,
 'operatingCashflow': 7104999936,
 'revenueGrowth': 0.154,
 'grossMargins': 0.48826,
 'ebitdaMargins': 0.20465,
 'operatingMargins': -0.41627997,
 'financialCurrency': 'USD',
 'symbol': 'SPCX',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Space Exploration Technologies ',
 'longName': 'Space Exploration Technologies Corp.',
 'fiftyDayAverageChange': -7.1235657,
 'fiftyDayAverageChangePercent': -0.04212048,
 'twoHundredDayAverageChange': -7.1235657,
 'twoHundredDayAverageChangePercent': -0.04212048,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'ipoExpectedDate': '2026-06-12',
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'corporateActions': [],
 'preMarketTime': 1783338446,
 'regularMarketTime': 1783022400,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_7702894',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 2.8310313,
 'regularMarketPrice': 162.0,
 'marketState': 'PRE',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 1781271000000,
 'preMarketChange': 2.399994,
 'preMarketChangePercent': 1.4814777,
 'preMarketPrice': 164.4,
 'regularMarketChange': 4.4600067,
 'regularMarketDayRange': '155.88 - 162.16',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 169218092,
 'fiftyTwoWeekLowChange': 14.889999,
 'fiftyTwoWeekLowChangePercent': 0.10121677,
 'fiftyTwoWeekRange': '147.11 - 225.64',
 'fiftyTwoWeekHighChange': -63.64,
 'fiftyTwoWeekHighChangePercent': -0.28204218,
 'fiftyTwoWeekChangePercent': 0.65237284,
 'epsTrailingTwelveMonths': -0.68,
 'epsForward': 0.19667,
 'epsCurrentYear': -0.42,
 'priceEpsCurrentYear': -385.7143,
 'displayName': 'Space Exploration',
 'trailingPegRatio': None}

In [7]:
data.calendar

{'Earnings Date': [],
 'Earnings High': -0.11,
 'Earnings Low': -0.2,
 'Earnings Average': -0.152,
 'Revenue High': 8025000000,
 'Revenue Low': 5300000000,
 'Revenue Average': 6944675000}

In [8]:
data.analyst_price_targets

{'current': 162.0,
 'high': 310.0,
 'low': 62.0,
 'mean': 188.57143,
 'median': 190.0}

In [10]:
data.quarterly_income_stmt

                                                      2026-03-31    2025-03-31
Tax Effect Of Unusual Items                         4.400000e+06 -5.880000e+06
Tax Rate For Calcs                                  4.000000e-01  2.100000e-01
Normalized EBITDA                                  -1.175000e+09  1.404000e+09
Total Unusual Items                                 1.100000e+07 -2.800000e+07
Total Unusual Items Excluding Goodwill              1.100000e+07 -2.800000e+07
Net Income From Continuing Operation Net Minori... -4.276000e+09 -5.280000e+08
Reconciled Depreciation                             2.442000e+09  1.443000e+09
Reconciled Cost Of Revenue                          2.388000e+09  1.962000e+09
EBITDA                                             -1.164000e+09  1.376000e+09
EBIT                                               -3.606000e+09 -6.700000e+07
Net Interest Income                                -4.510000e+08 -3.300000e+08
Interest Expense                                    6.640000e+08  4.470000e+08
Interest Income                                     2.130000e+08  1.170000e+08
Normalized Income                                  -4.282600e+09 -5.058800e+08
Net Income From Continuing And Discontinued Ope... -4.276000e+09 -5.280000e+08
Total Expenses                                      6.648000e+09  4.012000e+09
Total Operating Income As Reported                 -1.943000e+09  2.700000e+07
Diluted Average Shares                              1.060700e+10  1.060700e+10
Basic Average Shares                                1.060700e+10  1.060700e+10
Diluted EPS                                        -4.100000e-01 -4.977800e-02
Basic EPS                                          -4.100000e-01 -4.977800e-02
Diluted NI Availto Com Stockholders                -4.382000e+09 -5.280000e+08
Net Income Common Stockholders                     -4.382000e+09 -5.280000e+08
Otherunder Preferred Stock Dividend                -5.650000e+08           NaN
Preferred Stock Dividends                           6.710000e+08           NaN
Net Income                                         -4.276000e+09 -5.280000e+08
Net Income Including Noncontrolling Interests      -4.276000e+09 -5.280000e+08
Net Income Continuous Operations                   -4.276000e+09 -5.280000e+08
Tax Provision                                       6.000000e+06  1.400000e+07
Pretax Income                                      -4.270000e+09 -5.140000e+08
Other Income Expense                               -1.865000e+09 -2.390000e+08
Other Non Operating Income Expenses                -1.876000e+09 -2.110000e+08
Special Income Charges                              1.100000e+07 -2.800000e+07
Impairment Of Capital Assets                        0.000000e+00  2.400000e+07
Restructuring And Mergern Acquisition              -1.100000e+07  4.000000e+06
Net Non Operating Interest Income Expense          -4.510000e+08 -3.300000e+08
Interest Expense Non Operating                      6.640000e+08  4.470000e+08
Interest Income Non Operating                       2.130000e+08  1.170000e+08
Operating Income                                   -1.954000e+09  5.500000e+07
Operating Expense                                   4.260000e+09  2.050000e+09
Research And Development                            3.514000e+09  1.557000e+09
Selling General And Administration                  7.460000e+08  4.930000e+08
Gross Profit                                        2.306000e+09  2.105000e+09
Cost Of Revenue                                     2.388000e+09  1.962000e+09
Total Revenue                                       4.694000e+09  4.067000e+09
Operating Revenue                                   4.694000e+09  4.067000e+09

In [12]:
data.history(period='5d')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-06-26 00:00:00-04:00,150.619995,158.399994,148.509995,153.229996,126932900,0.0,0.0
2026-06-29 00:00:00-04:00,157.360001,166.169998,151.740005,164.190002,81443100,0.0,0.0
2026-06-30 00:00:00-04:00,163.380005,172.399994,161.639999,170.860001,82047500,0.0,0.0
2026-07-01 00:00:00-04:00,171.570007,171.740005,155.000000,157.539993,109317600,0.0,0.0
2026-07-02 00:00:00-04:00,159.729996,162.160004,155.880005,162.000000,61257100,0.0,0.0

In [13]:
tickers = yf.Tickers('MSFT AAPL GOOG')
tickers.tickers['AAPL'].info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 166000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1782864000,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 294.38,
 'open': 294.085,
 'dayLow': 293.68,
 'dayHigh': 309.42,
 'regularMarketPreviousClose': 294.38,
 'regularMarketOpen': 294.085,
 'regularMarketDayLow': 293.68,
 'regularMarketDayHigh': 309.42,
 'dividendRate': 1.08,
 'dividendYield': 0.35,
 'exDividendDate': 1778457600,
 'payoutRatio': 0.1259,
 'fiveYearAvgDividendYield': 0.5,
 'beta': 1.097,
 'trailingPE': 37.319225,
 'forwardPE': 32.119114,
 'volume': 75400626,
 'regularMarketVolume': 75400626,
 'averageVolume': 54341529,
 'averageVolume10days': 86176830,
 'averageDailyVolume10Day': 86176830,
 'bid': 307.23,
 'ask': 309.98,
 'bidSize': 4,
 'askSize': 4,
 'marketCap': 4532958920704,
 'nonDilutedMarketCap': 4532958682280,
 'fiftyTwoWeekLow': 201.5,
 'fiftyTwoWeekHigh': 317.4,
 'allTimeHigh': 317.4,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 10.041065,
 'fiftyDayAverage': 293.523,
 'twoHundredDayAverage': 270.69144,
 'trailingAnnualDividendRate': 1.04,
 'trailingAnnualDividendYield': 0.0035328486,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4549162565632,
 'profitMargins': 0.27152002,
 'floatShares': 14662534368,
 'sharesOutstanding': 14687356000,
 'sharesShort': 144248476,
 'sharesShortPriorMonth': 138782718,
 'sharesShortPreviousMonthDate': 1778803200,
 'dateShortInterest': 1781481600,
 'sharesPercentSharesOut': 0.0098,
 'heldPercentInsiders': 0.01631,
 'heldPercentInstitutions': 0.65779,
 'shortRatio': 2.88,
 'shortPercentOfFloat': 0.0098,
 'impliedSharesOutstanding': 14687356000,
 'bookValue': 7.26,
 'priceToBook': 42.511017,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1774656000,
 'earningsQuarterlyGrowth': 0.194,
 'netIncomeToCommon': 122575003648,
 'trailingEps': 8.27,
 'forwardEps': 9.60892,
 'pegRatio': 2.49,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 10.077,
 'enterpriseToEbitda': 28.437,
 '52WeekChange': 0.47001672,
 'SandP52WeekChange': 0.20116603,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1778457600,
 'quoteType': 'EQUITY',
 'currentPrice': 308.63,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 315.09048,
 'targetMedianPrice': 315.0,
 'recommendationMean': 2.02128,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 42,
 'totalCash': 68507000832,
 'totalCashPerShare': 4.664,
 'ebitda': 159975997440,
 'totalDebt': 84710998016,
 'quickRatio': 0.906,
 'currentRatio': 1.07,
 'totalRevenue': 451442016256,
 'debtToEquity': 79.548,
 'revenuePerShare': 30.534,
 'returnOnAssets': 0.26229,
 'returnOnEquity': 1.4147099,
 'grossProfits': 216070995968,
 'freeCashflow': 101090746368,
 'operatingCashflow': 140222005248,
 'earningsGrowth': 0.218,
 'revenueGrowth': 0.166,
 'grossMargins': 0.47862,
 'ebitdaMargins': 0.35437,
 'operatingMargins': 0.32275,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'priceEpsCurrentYear': 35.253628,
 'fiftyDayAverageChange': 15.106995,
 'fiftyDayAverageChangePercent': 0.051467836,
 'twoHundredDayAverageChange': 37.93857,
 'twoHundredDayAverageChangePercent': 0.1401543,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'corporateActions': [],
 'preMarketTime': 1783338688,
 'regularMarketTime': 1783022401,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 4.840682,
 'regularMarketPrice': 308.63,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'preMarketChange': -1.980011,
 'preMarketChangePercent': -0.64154845,
 'preMarketPrice': 306.65,
 'regularMarketChange': 14.25,
 'regularMarketDayRange': '293.68 - 309.42',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 54341529,
 'fiftyTwoWeekLowChange': 107.130005,
 'fiftyTwoWeekLowChangePercent': 0.5316626,
 'fiftyTwoWeekRange': '201.5 - 317.4',
 'fiftyTwoWeekHighChange': -8.769989,
 'fiftyTwoWeekHighChangePercent': -0.027630717,
 'fiftyTwoWeekChangePercent': 47.00167,
 'dividendDate': 1778716800,
 'earningsTimestamp': 1785441600,
 'earningsTimestampStart': 1785441600,
 'earningsTimestampEnd': 1785441600,
 'earningsCallTimestampStart': 1785441600,
 'earningsCallTimestampEnd': 1785441600,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 8.27,
 'epsForward': 9.60892,
 'epsCurrentYear': 8.75456,
 'marketState': 'PRE',
 'displayName': 'Apple',
 'trailingPegRatio': 2.4938}